export const TEST_ACTION = "TEST_ACTION";
export const GET_DATE_RANGES = "GET_DATE_RANGES";

export const LOAD_LANDING_HERO = "LOAD_LANDING_HERO";
export const CONFIRM_CALENDAR_DATES = "CONFIRM_CALENDAR_DATES";
export const RENDER_CALENDAR_MODAL_DATE = "RENDER_CALENDAR_MODAL_DATE";
