export const TEST_ACTION = "TEST_ACTION";
export const GET_DATE_RANGES = "GET_DATE_RANGES";

export const LOAD_LANDING_HERO = "LOAD_LANDING_HERO";
export const CONFIRM_CALENDAR_DATES = "CONFIRM_CALENDAR_DATES";
export const RENDER_CALENDAR_MODAL_DATE = "RENDER_CALENDAR_MODAL_DATE";
export const SHOW_CONFIRM_DATES = "SHOW_CONFIRM_DATES";


export const SEND_REQUEST_TO_DB = "SEND_REQUEST_TO_DB";


export const HANDLE_NEXT_BTN_BOOKING_MODAL = "HANDLE_NEXT_BTN_BOOKING_MODAL";
export const HANDLE_BACK_BTN_BOOKING_MODAL = "HANDLE_BACK_BTN_BOOKING_MODAL";

export const VALIDATE_BOOKING_FORM_ON_SUBMIT = "VALIDATE_BOOKING_FORM_ON_SUBMIT";
export const VALIDATE_BOOKING_FORM_ON_TYPING = "VALIDATE_BOOKING_FORM_ON_TYPING";


export const ON_SUBMIT_CLOSE_CONFIRM_BOOK_FORM = "ON_SUBMIT_CLOSE_CONFIRM_BOOK_FORM"
export const SHOW_CONFIRM_BOOKED_MODAL = "SHOW_CONFIRM_BOOKED_MODAL";
export const RESET_ADD_DB_ENTRY_API_STATUS = "RESET_ADD_DB_ENTRY_API_STATUS";
export const CLEAR_BOOK_FORM = "CLEAR_BOOK_FORM";
export const SELECT_SVC = "SELECT_SVC";